export const DEFAULT_DEPTS = [
  {
    id: "dept-1",
    name: "Civil Engineering",
    description: "Handles all civil construction works, materials, and site activities.",
    yearBudget: 250000,
    monthBudget: 21000,
  },
  {
    id: "dept-2",
    name: "Structural Department",
    description: "Responsible for design, analysis, and procurement of structural materials like steel, cement, etc.",
    yearBudget: 200000,
    monthBudget: 18000,
  },
  {
    id: "dept-3",
    name: "Electrical Department",
    description: "Manages electrical materials, wiring, fixtures, and lighting equipment procurement.",
    yearBudget: 150000,
    monthBudget: 13000,
  },
  {
    id: "dept-4",
    name: "Mechanical Department",
    description: "Procurement of mechanical tools, machinery, and maintenance items.",
    yearBudget: 140000,
    monthBudget: 12000,
  },
  {
    id: "dept-5",
    name: "Procurement / Purchase",
    description: "Centralized purchase operations for all departments and vendor management.",
    yearBudget: 100000,
    monthBudget: 8500,
  },
  {
    id: "dept-6",
    name: "Project Management",
    description: "Oversees project execution, progress tracking, and resource allocation.",
    yearBudget: 160000,
    monthBudget: 14000,
  },
  {
    id: "dept-7",
    name: "Quality Control",
    description: "Manages inspection, testing, and compliance of construction materials.",
    yearBudget: 80000,
    monthBudget: 7000,
  },
  {
    id: "dept-8",
    name: "Safety Department",
    description: "Ensures workplace safety, PPE procurement, and compliance with safety regulations.",
    yearBudget: 60000,
    monthBudget: 5000,
  },
  {
    id: "dept-9",
    name: "Human Resources (HR)",
    description: "Handles employee hiring, training, welfare, and HR-related procurement.",
    yearBudget: 70000,
    monthBudget: 6000,
  },
  {
    id: "dept-10",
    name: "MIS / IT",
    description: "Procures IT infrastructure, software tools, networking, and communication systems.",
    yearBudget: 90000,
    monthBudget: 7500,
  },
  {
    id: "dept-11",
    name: "Finance & Accounts",
    description: "Manages budgeting, payment processing, and vendor billing.",
    yearBudget: 120000,
    monthBudget: 10000,
  },
  {
    id: "dept-12",
    name: "Transport & Logistics",
    description: "Handles vehicle procurement, fuel, logistics, and material movement.",
    yearBudget: 100000,
    monthBudget: 8500,
  },
  {
    id: "dept-13",
    name: "Administration",
    description: "Responsible for office supplies, facility maintenance, and general admin purchases.",
    yearBudget: 50000,
    monthBudget: 4200,
  },
];
